language: python
env:
 - TOX_ENV=py36
 - TOX_ENV=py35
 - TOX_ENV=py34
 - TOX_ENV=py33
 - TOX_ENV=py27
 - TOX_ENV=flake8
cache: pip
install:
  - pip install tox-travis codecov
script:
  - tox
  - tox -e flake8
after_success:
- codecov
