language: python
install:
- pip install tox-travis codecov
jobs:
  include:
  - stage: test
    cache: pip
    env:
    - TOX_ENV=py34
    - TOX_ENV=py27
    - TOX_ENV=flake8
    script:
    - tox -e $TOX_ENV
    after_success:
    - codecov
  - stage: build
    script:
    - pip install .
    - python -m docere.cli render --knowledge-repo tests/data/kr
  - stage: deploy
    #if: type = push AND repo = harterrt/docere AND branch = master
    - ls --recursive output
    - pip install awscli
    - aws s3 cp --recursive output/ s3://docere-test/ --acl "public-read"
    skip_cleanup: true
