language: python
install:
- pip install tox-travis codecov
jobs:
  include:
  - stage: test
    env:
    - TOX_ENV=py34
    - TOX_ENV=py27
    - TOX_ENV=flake8
    cache: pip
    script:
    - tox -e $TOX_ENV
    after_success:
    - codecov
  - stage: deploy
    if: repo = harterrt/docere AND branch = master AND type = push
    script:
    - pip install awscli
    - pip install .
    - python -m docere.cli render --knowledge-repo tests/data/kr
    - aws s3 cp --recursive output/ s3://docere-test/ --acl "public-read"
    skip_cleanup: true
