language: python
env:
- TOX_ENV=py34
# - TOX_ENV=py27
# - TOX_ENV=flake8
cache: pip
install:
- pip install tox-travis codecov
script:
- echo Passes
# - tox -e $TOX_ENV
after_success:
- codecov
deploy:
  provider: s3
  access_key_id: AKIAIWS75WFDTIQQVFNQ
  secret_access_key:
    secure: ETBTamb9XgsGvNWmoCy3fbUErO2gzz2oJsTwmq/Wyw76pUhH4CwTxkof2+u/jNTw+z1xLIZN1/kp6vc13F2Iy0ZW8K4favGMxXvzTMoYkEH4jr6lRftguLjAfB5pBGZL9gL44tnKI6XjwwgJ94q33qgLRIMNZQuN1e5pgzyAH4CsKqLEPsKZPKhUTFqcIcQEX8jzDP9zQtTkTYEsgfmQHbgNnyxAhE3IyTd1VpRgRJLfYzBZEQE8aLHGwLNhzpe/yz+ymQaBs7mgroa65rOllfXS/hlESexDhm5vHO7QCOnTVrYo6Yy4VR9tLBH5/WlxkCofaxiuwLhFmZUjHIZD7XJoqPzAIuzAkGGueaTqB5UULcl323ObvUjq1efxqny6juRIJHHYnqZbXFkC+OYsHaIPGDya1y5DpdGihwJ20vjcqOFIWiXBILYUHmE18yocY97X0QUvsf0atO+GgRwcWXyZ9Z8i309wrncIjtORKe/N/DRg1L6eDl7EsHPz6mau22EbI/AU/8+5TD9rnBZp3Wr9JsWTfLTjR71NHIGdH3Tg8+Se0/fK1AD9fLZ4rQOTKG6t1P/qM97pjcnlhQUQq5DtXsszQ4wEqimymRn+LiVFMI7/VGUm6s0HILfT+QOU0RjsbEhEWRLuHaLPRqF0Y48gTCJgiN1+8x8YXH3J9Pc=
  bucket: docere-test
  local-dir: output
  acl: public_read
#  on:
#    repo: harterrt/docere
#    branch: ci
