language: python
install:
- pip install tox-travis codecov
jobs:
  include:
  - stage: test
    env:
    - TOX_ENV=py34
    cache: pip
    script:
    - echo Passes!
    after_success:
    - codecov
  - stage: deploy
    script:
    - pip install awscli
    - pip install .
    - python -m docere.cli render --knowledge-repo tests/data/kr
    - aws s3 cp --recursive output/ s3://docere-test/ --acl "public-read"
    skip_cleanup: true
