language: python
env:
 - TOX_ENV=py34
 - TOX_ENV=py27
 - TOX_ENV=flake8
cache: pip
install:
  - pip install tox-travis codecov
script:
  - echo Passes! #tox -e $TOX_ENV
after_success:
- codecov
jobs:
  include:
    - stage: deploy
      # on:
      #   branch: master
      #   repo: harterrt/docere
      #   condition: "$TRAVIS_PULL_REQUEST" = "false"
      script: 
        - pip install .
        - python -m docere.cli render --knowledge-repo tests/data/kr
        - ls
