language: python
install:
- pip install tox-travis codecov
cache: pip
env:
- TOX_ENV=py34
- TOX_ENV=py27
- TOX_ENV=flake8
jobs:
  include:
  - stage: test
    script:
    - tox -e $TOX_ENV
    after_success:
    - codecov
  - stage: deploy
    if: type = push AND repo = harterrt/docere AND branch = master
    script:
    - echo $TRAVIS_PULL_REQUEST
    - echo $TRAVIS_PULL_REQUEST == "false"
    - pip install awscli
    - pip install .
    - python -m docere.cli render --knowledge-repo tests/data/kr
    - aws s3 cp --recursive output/ s3://docere-test/ --acl "public-read"
    skip_cleanup: true
