language: python
install:
- pip install tox-travis codecov
env:
- TOX_ENV=py34
- TOX_ENV=py27
- TOX_ENV=flake8
cache: pip
script:
- tox -e $TOX_ENV
after_success:
- codecov
jobs:
  include:
  - stage: deploy
    script:
    - pip install .
    - python -m docere.cli render --knowledge-repo tests/data/kr
    deploy: &s3
      provider: s3
      local_dir: output
      bucket: docere-test
      access_key_id: 
        secure: Gvl0q7nXuCDT9IlY3FOQn640srhory5oZNXhzwOvpaUAhIqdDNlhejKq7sCnIVrv3EsOibaTn/9j0Q/3h2X0BpeFdeQMNXhu9Yx/IG2cg7mefFE/tP4B+mkvXTAq2ZIVkfoxqAFE25Y9L26RAqm2zWANfr+XEWnnU4jnowRbc6+z5vV7dAJ7DJwmMBssZptMQw/0FuXpM7ZRh8ZMUANTqCMYVlm4Ft2lASb6B5pqpdGdbePdurGDm7njDu5dsBBliZecBMXA7FRItw/LKJBqr+XsvrTj0fBmSv7Ua6rKtlYinn/LVG32EygXhGVB95JtK+o8THdGe84iiAmJyXAUIRMjWFbNJDVlFYyGdHKfqdRv1vvjteVWLfY9aUpo34wuBl3q75y0v5X4YsvIKpIiEs7HvqaymUMbVzJ9MrdSaeBEka2/Y2zqSJrgsZ8dFoTn1J0Ap2jE4iaKqiJ6q9KP8UgC9w2d2amskjjywI4ZFhq75nJ4NUklA9hmonuleGxikM/6nzLgugDqA2Vr7tkz/lH2KyJ5g8D8UdAtW83a0leNgKZhhW/XvC9xskt81eZVnXUue/EmhM98S5zI7EvfITw8YHnq9q0ADPQj74IrSHEWM+8rLb1fKByYe/RyPdTc5nZUJVqlYDomhVjXNDzWc+9CL/JBOb815bszDY//fgU=
      secret_access_key:
        secure: KWJh2pVTzGMiJBIiuRk55unrgdlB3FRpw3T0lFP+gq8zLE0BWIcWaqMkYhY1vGSveLgneerxKIhWB/2WG039EEBKO+S34IvhFq+zEL4MVHbNT+UjgXeg0L7SE+SBgfQFk5dxMnU8XkdS7iTWWuoxkatQUnfOX/JMbIcRMnOqo+kLfjDI47KJCMLipoMwezLNMEm7TJygHxiu2DCPr2g378N9ZMBwN1FYBgmMqSCIFsifeIDdAwz3amjFZ0Nk4IhsD22Q3lheGJFK9DySg0uo3D2sBrJScqBHijeeApgigDaY9eENxaz0mD+VlgLKx1Y0XwV7QXXGiWf+hv5KBQnBj+NkneqNmzYcRFr+NY7/NUAqelZv7WMXFzsEAs02oHeVmaQ5cm16prc12CU+hZYPfW/gFDQSpdEKXYNbgiJAwMmy0+xH70n0MGm/qcsmxldmJG1k5PNBmFeYIANRhx3ZhZnzc/79MtEbmzphVpv/a72JZXJasA+o2876t1eNg3APw0X/HiuLV12L7YZ9+6EOutSQOz+eO9PlrFsUAhwElaKseMYhCXmnA98T/LKPno+23zDk5gni9JETLopP/RRWbLhkpQE7u4SOVZtNVRenc4i5BAlCctmF97vlJsrDUII24MVpFjCSUWtGPAKgbtHSDiiHz+1niJxPidYh6IDqC6c=
      acl: public_read
