language: python
install:
- pip install tox-travis codecov
env:
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=flake8
cache: pip
script:
- tox -e $TOX_ENV
after_success:
- codecov
jobs:
  include:
  - stage: deploy
    skip-cleanup: true
    script:
    - pip install .
    - python -m docere.cli render --knowledge-repo tests/data/kr
    deploy: &s3
      skip-cleanup: true
      provider: s3
      local_dir: output
      bucket: docere-test
      acl: public_read
