version: 2.1

templates:
  - &default_python "cimg/python:3.8"
  - test_template: &test_template
      steps:
        - checkout
        - run:
            name: Run tox
            command: |
              pip install -U tox codecov
              tox -e ${CIRCLE_JOB}
              codecov

orbs:
  s3: circleci/aws-s3@2.0.0

jobs:
  py38:
    <<: *test_template
    docker:
      - image: cimg/python:3.8
  py39:
    <<: *test_template
    docker:
      - image: cimg/python:3.9
  flake8:
    <<: *test_template
    docker:
      - image: *default_python
  deploy_demo:
    steps:
      - checkout
      - run:
          name: "Run Docere"
          command: |
            pip install .
            docere render --knowledge-repo tests/data/kr
      - s3/sync:
          arguments: |
            --acl public-read \
            --delete
          from: output
          to: s3://docere-test
    docker:
      - image: *default_python

workflows:
  version: 2
  build:
    jobs:
      - flake8
      - py38
      - py39
      - deploy_demo:
          filters:
            branches:
              only:
                - master
                - main
