version: 2.1

test_template: &test_template
  steps:
    - checkout
    - run:
        name: Run tox
        command: |
          pip install -U tox
          tox -e ${CIRCLE_JOB}

orbs:
  s3: circleci/aws-s3@2.0.0

jobs:
  py38:
    <<: *test_template
    docker:
      - image: cimg/python:3.8
  py39:
    <<: *test_template
    docker:
      - image: cimg/python:3.9
  deploy_demo:
    steps:
      - checkout
      - run:
          name: "Run Docere"
          command: |
            pip install .
            docere render --knowledge-repo tests/data/kr
      - s3/sync:
          arguments: |
            --acl public-read \
            --delete
          from: output
          to: docere-test
    docker:
      - image: cimg/python:3.8


workflows:
  version: 2
  build:
    jobs:
      - py38
      - py39
      - deploy_demo:
          filters:
            branches:
              only:
                - master
                - main
